basePath: /api/v1
definitions:
  rest.CreateEmployeeRequest:
    properties:
      cpf:
        type: string
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      pis:
        type: string
    required:
    - cpf
    - email
    - first_name
    - last_name
    - pis
    type: object
  rest.CreateEmployeeResponse:
    properties:
      id:
        type: string
    type: object
  rest.Employee:
    properties:
      cpf:
        type: string
      created_at:
        type: string
      email:
        type: string
      enabled:
        type: boolean
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      pis:
        type: string
      updated_at:
        type: string
    type: object
  rest.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      error:
        example: status bad request
        type: string
    type: object
  rest.HTTPResponse:
    properties:
      code:
        example: 200
        type: integer
      message:
        example: a message
        type: string
    type: object
  rest.SearchEmployeesResponse:
    properties:
      employees:
        items:
          $ref: '#/definitions/rest.Employee'
        type: array
      next_page_token:
        type: string
    type: object
  rest.UpdateEmployeeRequest:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
    type: object
info:
  contact:
    email: contato@coding4u.com.br
    name: Coding4u
  description: Swagger API for Golang Project Employee.
  termsOfService: http://swagger.io/terms/
  title: Employee Swagger API
  version: "1.0"
paths:
  /employees:
    get:
      consumes:
      - application/json
      description: Search for employee employees by `filter`. if the page size is
        empty, 10 will be considered.
      operationId: searchEmployees
      parameters:
      - in: query
        name: first_name
        type: string
      - in: query
        name: last_name
        type: string
      - default: 10
        in: query
        name: page_size
        type: integer
      - in: query
        name: page_token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/rest.SearchEmployeesResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.HTTPError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/rest.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: search employees by filter
      tags:
      - Employee
    post:
      consumes:
      - application/json
      description: create employee
      operationId: createEmployee
      parameters:
      - description: JSON body to create a new employee
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/rest.CreateEmployeeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.CreateEmployeeResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/rest.HTTPError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/rest.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: create a employee
      tags:
      - Employee
  /employees/{id}:
    get:
      consumes:
      - application/json
      description: Router for find a employee
      operationId: findEmployee
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.Employee'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.HTTPError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/rest.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: find a employee
      tags:
      - Employee
    put:
      consumes:
      - application/json
      description: Router for update a employee
      operationId: updateEmployee
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: string
      - description: JSON body to update a new employee
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/rest.UpdateEmployeeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.HTTPResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.HTTPError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/rest.HTTPError'
      security:
      - ApiKeyAuth: []
      summary: update a employee
      tags:
      - Employee
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
