version: '3.4'

services:
  employee-service:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      ENV: dev
      ELASTIC_APM_SERVICE_NAME: employee-service
    ports:
      - $EMPLOYEE_GRPC_PORT:50051
      - $EMPLOYEE_REST_PORT:8080
    volumes:
      - .:/go/src/
    networks:
      - employee
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

networks:
  employee:
    driver: bridge
